### ISSUE TITLE
Typography - reduce the line length

### ISSUE THREAD

**Issue by revelt** [MrBenJ/modern-js-by-example#64]
In professional typography, the recommended line length is [45-90 characters](https://practicaltypography.com/line-length.html). Currently, we're at around 120 - twice the recommended. Let's narrow-down the columns and make the text more readable.

**Comment by MrBenJ** [comment]
Hey! Thanks for the comment :).

I'm not sure if this totally applies to my book since the preferred way to view the book is on https://www.modernjsbyexample.net - which is responsive and the line length in the markdown files will just wrap when it gets to the edge of the container.

Are you suggesting to change the width of the page container to ensure the line length goes to 45-90 characters? There's a spot for that here in the global css:

https://github.com/MrBenJ/modern-js-by-example/blob/master/src/components/Layout/style-global.css#L630

If I get the time to turn this into a print/ebook version, I'll definitely take your advice :).

Is narrowing the width of the container what you'd like me to do? 

Thanks!

**Comment by revelt** [comment]
> Is narrowing the width of the container what you'd like me to do?
yap
